version: '3'
services: 
  web:
    restart: always
    build: .
    volumes: 
      - ./:/var/www/
    depends_on: 
      - db

  db:
    image: mysql:5.7
    environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: app
       MYSQL_USER: root
       MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - 'mysqldb:/var/lib/mysql/'

  nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8000:80"
    volumes: 
      - ./:/var/www
    depends_on: 
      - web
volumes:
  mysqldb:
