version: '3'
services: 
  web:
    restart: always
    build: .
    volumes: 
      - ./:/var/www/
    depends_on: 
      - db

  db:
    image: mysql
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: app-payment-db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: rootpasswordapp
    volumes:
      - "./.docker/dbdata:/var/lib/mysql/"

  nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8000:80"
    volumes: 
      - ./:/var/www
    depends_on: 
      - web
volumes:
  mybd:
    driver: local